### ISSUE TITLE
Bug: [Installing azul jdk for aarch64 result in x86 binaries]

### ISSUE THREAD

**Issue by burqen** [sdkman/sdkman-disco-integration#9] opened 2023-04-20 12:59 UTC
**Bug report**
Installing zulu distro of java on Mac with aarch64 architecture result in x86 installation.

**To reproduce**
Install java 17.0.6-zulu, 11.0.18-zulu and 8.0.362-zulu
```
$ sdk install java 17.0.6-zulu
$ sdk install java 11.0.18-zulu
$ sdk install java 8.0.362-zulu
```
Check installation
```
$ sdk list java
================================================================================
Available Java Versions for macOS ARM 64bit
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
... skipping rows for brevity ...
 Zulu          |     | 20           | zulu    |            | 20-zulu             
               |     | 20.fx        | zulu    |            | 20.fx-zulu          
               |     | 20.0.1       | zulu    |            | 20.0.1-zulu         
               |     | 20.0.1.fx    | zulu    |            | 20.0.1.fx-zulu      
               |     | 19.0.2       | zulu    |            | 19.0.2-zulu         
               |     | 19.0.2.fx    | zulu    |            | 19.0.2.fx-zulu      
               |     | 19.0.1       | zulu    |            | 19.0.1-zulu         
               |     | 19.0.1.fx    | zulu    |            | 19.0.1.fx-zulu      
               |     | 17.0.7       | zulu    |            | 17.0.7-zulu         
               | >>> | 17.0.6       | zulu    | installed  | 17.0.6-zulu         
               |     | 17.0.6.fx    | zulu    |            | 17.0.6.fx-zulu      
               |     | 17.0.5       | zulu    |            | 17.0.5-zulu         
               |     | 17.0.5.fx    | zulu    |            | 17.0.5.fx-zulu      
               |     | 11.0.19      | zulu    |            | 11.0.19-zulu        
               |     | 11.0.18      | zulu    | installed  | 11.0.18-zulu        
               |     | 11.0.18.fx   | zulu    |            | 11.0.18.fx-zulu     
               |     | 11.0.17      | zulu    |            | 11.0.17-zulu        
               |     | 11.0.17.fx   | zulu    |            | 11.0.17.fx-zulu     
               |     | 8.0.362      | zulu    | installed  | 8.0.362-zulu        
               |     | 8.0.362.fx   | zulu    |            | 8.0.362.fx-zulu     
               |     | 8.0.352      | zulu    |            | 8.0.352-zulu        
               |     | 8.0.352.fx   | zulu    |            | 8.0.352.fx-zulu 
```
Check the java executable and see that all of them are for x86.
```
$ pwd
/Users/home/.sdkman/candidates/java/17.0.6-zulu/bin
$ file java
java: Mach-O 64-bit executable x86_64
```
```
$ pwd
/Users/antonpersson/.sdkman/candidates/java/11.0.18-zulu
$ file bin/java
bin/java: Mach-O 64-bit executable x86_64
```
```
$ pwd
/Users/antonpersson/.sdkman/candidates/java/8.0.362-zulu
$ file bin/java
bin/java: Mach-O 64-bit executable x86_64
```

**System info**
OS
```
$ uname -a
Darwin xxx-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000 arm64
```
Shell
```
$ zsh --version
zsh 5.5.1 (x86_64-apple-darwin16.7.0)
```
Sdkman
```
$ sdk version

SDKMAN!
script: 5.18.1
native: 0.1.3
```

**Comment by eddumelendez** [comment] 2023-05-01 21:51
Everything looks good to me. I just tried

```
Downloads/git/spring-boot  main ✗                                                                                                           2h6m ◒  ⍉
▶ cd ~/.sdkman/candidates/java/17.0.6-zulu/bin

Restored java version to 8.0.362-librca (default)

java/17.0.6-zulu/bin
▶ file java
java: Mach-O 64-bit executable arm64
```

**Comment by eddumelendez** [comment] 2023-05-01 22:05
can you share the output of `sdk config`? are you running the command on a terminal with rosetta enabled?

**Comment by eddumelendez** [comment] 2023-05-03 21:59
I'll close the issue due to can't reproduce. Feel free to re-open it and provide more info.

**Closed by eddumelendez** 2023-05-03 21:59 UTC
Labels: bug
